#
# This is the configuration file of the software.
#

###################
# System settings #
###################

# database path
db_path: ~/workspace/supergossip/db/

######################
# Routing parameters #
######################

# Maximum supernode table of an ordinary node
max_table_size_on: 6

# Timeout of select call on sockets
timeout: 30

# The interval of requesting supernodes
request_interval: 180

# Number of supernodes requested each time
request_number: 5

# The interval of updating authority and hub values
update_routing_interval: 300

# Force this node to be supernode
force_supernode: false

# Force this node to be ordinary node
force_oridnary_node: false

# Interval of watching if this node can be promoted to a supernode
supernode_watch_interval: 3600

# Minimum download speed to become a supernode in KB/s unit
min_download_speed: 30

# Minimum upload speed to become a supernode in KB/s unit
min_upload_speed: 20

# Minimum online rate (hours per day) to become a supernode
min_online_rate: 4
