#
# This is the configuration file of the software.
#

###################
# System settings #
###################

# database path
db_path: ~/workspace/supergossip/db/

######################
# Routing parameters #
######################

# Maximum supernode table of an ordinary node
max_table_size_on: 6

# Timeout of select call on sockets
timeout: 30

# The interval of requesting supernodes
request_interval: 180

# Number of supernodes requested each time
request_number: 5

# The interval of updating authority and hub values
update_routing_interval: 300
